#!/bin/bash -e
# Quick 'n' dirty thrash test script for reproducing infrequent failures.
# For best effects do "ulimit -c unlimited" first, then meditate on the core file when it stops.

PROG=./b2test
#PROG=b2test.valgrind

TMP=`tempfile -d . -p TEMP`

trap "echo; cat $TMP; rm $TMP" ERR
trap "echo ; echo" exit

for x in `seq 1 100`; do
	echo -ne "running $x \r"
	$PROG 2>&1 > $TMP
done

rm $TMP

